---
title: "X-Culture Pilot Analysis"
author: "csaund"
date: "13/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(pwr)
library(ordinal)
```

### Gesture Map
* West 1 - Unpolite
* West 2 - Entity
* West 3 - Audience
* West 4 - Anything
* West 5 - Specific

* East 1 - Color Fists
* East 2 - Battle
* East 3 - Arm Cross
* East 4 - Rainbow


### Load and clean data 
```{r}

load_clean_data <- function(filepath) {
  data <- read.csv(filepath) %>% 
  dplyr::select(Answer.buttheads,
                Answer.close,
                Answer.cometogether,
                Answer.communicate,
                Answer.control,
                Answer.disagreement,
                Answer.worktogether,
                Answer.goal,
                Answer.getalong,
                Answer.overlap,
                Answer.protected,
                Answer.tension,
                Answer.unified,
                Answer.vid_id) 

  data$Answer.vid_id <- gsub("https://s3.us-east-2.amazonaws.com/metaphoric-gestures-x-culture/*", 
                             "\\1", 
                             data$Answer.vid_id)
  return(data)
}

d1 <- load_clean_data("./data/XC_5_western_gest_western_participants.csv")
d2 <- load_clean_data("./data/XC_gest_full_western_participants_5.csv")
d3 <- load_clean_data("./data/XC_gest_full_western_participants_4.csv")
d4 <- load_clean_data("./data/XC_pilot_gest_2.csv")

data <- rbind(d1, d2, d3, d4)

eastern <- data %>%
  filter(grepl("eastern", Answer.vid_id))

western <- data %>%
  filter(grepl("western", Answer.vid_id))

# need to get condition
make_it_pretty <- function(data, condition_name) {
  df <- data %>%
    mutate(condition=Answer.vid_id) %>%
    select(condition, Answer.buttheads,
                Answer.close,
                Answer.cometogether,
                Answer.communicate,
                Answer.control,
                Answer.disagreement,
                Answer.goal,
                Answer.getalong,
                Answer.overlap,
                Answer.protected,
                Answer.tension,
                Answer.unified,
                Answer.worktogether) %>%
    gather("statement_measure", score, 
                Answer.buttheads,
                Answer.close,
                Answer.cometogether,
                Answer.communicate,
                Answer.control,
                Answer.disagreement,
                Answer.goal,
                Answer.getalong,
                Answer.overlap,
                Answer.protected,
                Answer.tension,
                Answer.unified,
                Answer.worktogether)
  return(df)
}


west_cleaned <- make_it_pretty(western, "western")
east_cleaned <- make_it_pretty(eastern, "eastern")
```


Clean that shit up
```{r}
format_indiv_gesture <- function (gesture_num, condition1, condition2) {
  cleaned <- west_cleaned %>%
    mutate(ID=row_number()) %>%
    filter(grepl(gesture_num, condition)) %>%
    mutate(condition=(ifelse(grepl("-0", condition), "original", condition))) %>%
    mutate(condition=(ifelse(grepl("-1", condition), condition1, condition))) %>%
    mutate(condition=(ifelse(grepl("-2", condition), condition2, condition)))   
  return(cleaned)
}

west_gest_1_clean <- format_indiv_gesture("1-", "intertwine", "collide")
# all good

west_gest_2_clean <- format_indiv_gesture("2-", "open_palm", "in_chest")
# need more original

west_gest_3_clean <- format_indiv_gesture("3-", "no_circle", "palm_up")

west_gest_4_clean <- format_indiv_gesture("4-", "frame", "cover")
# need more cover

west_gest_5_clean <- format_indiv_gesture("5-", "bowl", "forward")
# need more original and forward

east_gest_1_clean <- east_cleaned %>%
  mutate(ID=row_number()) %>%
  filter(grepl("1-", condition))

east_gest_2_clean <- east_cleaned %>%
  mutate(ID=row_number()) %>%
  filter(grepl("2-", condition))

east_gest_3_clean <- east_cleaned %>%
  mutate(ID=row_number()) %>%
  filter(grepl("3-", condition))
```

Let's just blindly plot things and see what happens
```{r}
create_bar <- function(data) {
  bar_plot <- ggplot(data, aes(x=statement_measure, y=score, fill=condition)) + 
      geom_bar(stat="identity", position="dodge") + 
      facet_wrap(~statement_measure, scale="free")  
  return(bar_plot)
}

create_density <- function(data) {
  ## density of distributions
  density_plot <- ggplot(data, aes(x=score, fill=condition)) + 
    geom_density(alpha=0.3, stat="density", adjust=0.85) +
    facet_wrap(~statement_measure, scale="free") + 
    ggtitle("Unpolite Example distribution of statement ratings") 
  return(density_plot)
}

## get dat violin data

create_violin <- function(data) {
  violin_plot <- ggplot(data, aes(condition, score)) + 
    geom_violin(aes(fill=condition, alpha=0.5), scale="area", draw_quantiles = c(0.25, 0.5, 0.75)) +
    facet_wrap(~statement_measure) + 
    labs(
      title = "Violin plot (density) of ranked responses per condition by statement"   ,
      caption = "Horizontal lines are drawn at the 0.25, 0.5, and 0.75 quantiles of the distribution."
    )
  return(violin_plot)
}
```


```{r}
west_1_bar <- create_bar(west_gest_1_clean)
west_1_dense <- create_density(west_gest_1_clean)
west_1_violin <- create_violin(west_gest_1_clean)

west_1_west_2_bar <- create_bar(west_gest_2_clean)
west_2_dense <- create_density(west_gest_2_clean)
west_2_violin <- create_violin(west_gest_2_clean)

west_3_bar <- create_bar(west_gest_3_clean)
west_3_dense <- create_density(west_gest_3_clean)
west_3_violin <- create_violin(west_gest_3_clean)

west_4_bar <- create_bar(west_gest_4_clean)
west_4_dense <- create_density(west_gest_4_clean)
west_4_violin <- create_violin(west_gest_4_clean)

west_5_bar <- create_bar(west_gest_5_clean)
west_5_dense <- create_density(west_gest_5_clean)
west_5_violin <- create_violin(west_gest_5_clean)

east_1_bar <- create_bar(east_gest_1_clean)
east_1_dense <- create_density(east_gest_1_clean)
east_1_violin <- create_violin(east_gest_1_clean)

east_2_bar <- create_bar(east_gest_2_clean)
east_2_dense <- create_density(east_gest_2_clean)
east_2_violin <- create_violin(east_gest_2_clean)

easteast_3_bar <- create_bar(east_gest_3_clean)
east_3_dense <- create_density(east_gest_3_clean)
east_3_violin <- create_violin(east_gest_3_clean)
```
