---
title: "X-Culture Pilot Analysis"
author: "csaund"
date: "3/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(pwr)
library(ordinal)
```

U = unpolite
O = original
UT = U together
UF = U force

## Load

```{r}
load_and_clean <- function(filepath, condition_name) {
  df <- read.csv(filepath) %>%
    mutate(ID=row_number()) %>%
    mutate(condition=condition_name) %>%
    select(ID, condition,
           Answer.buttheads, Answer.disagreement, 
           Answer.getalong, Answer.goal,
           Answer.tension, Answer.unified,
           Answer.worktogether) %>%
    gather("statement_measure", score, Answer.disagreement,
            Answer.getalong, Answer.buttheads, Answer.worktogether,
            Answer.tension, Answer.goal, Answer.unified)
  return(df)
}
```

```{r}
uo <- load_and_clean('uo-pilot-noprime.csv', 'original')
uf <- load_and_clean('uf-pilot-noprime.csv', 'force')
ut <- load_and_clean('ut-pilot-noprime.csv', 'together')

total_unpolite <- rbind(uo, uf, ut)
```


#### Quick n dirty plotting
```{r}
## bar, but not working -- need to avg
unpolite_plot <- ggplot(total_unpolite, aes(x=statement_measure, y=score, fill=condition)) + 
    geom_bar(stat="identity", position="dodge") + 
    facet_wrap(~statement_measure, scale="free")

## density of distributions
unpolite_density <- ggplot(total_unpolite, aes(x=score, fill=condition)) + 
  geom_density(alpha=0.3, stat="density", adjust=0.85) +
  facet_wrap(~statement_measure, scale="free") + 
  ggtitle("Unpolite Example distribution of statement ratings")

## get dat violin data
unpolite_violin <- ggplot(total_unpolite, aes(condition, score)) + 
  geom_violin(aes(fill=condition, alpha=0.5), scale="area", draw_quantiles = c(0.25, 0.5, 0.75)) +
  facet_wrap(~statement_measure) + 
  labs(
    title = "Violin plot (density) of ranked responses per condition by statement"   ,
    caption = "Horizontal lines are drawn at the 0.25, 0.5, and 0.75 quantiles of the distribution."
  )
```



