---
title: "ACII19 Analysis -- Experiment 2"
author: "--"
date: "13/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(pwr)
library(ordinal)
library(gridExtra)
library(rlist)
library(xtable)
```

### Gesture Map
* West 1 - Unpolite
* West 2 - Entity
* West 3 - Audience
* West 4 - Anything
* West 5 - Specific


### Load and clean data 
```{r}

load_clean_data <- function(filepath) {
  data <- read.csv(filepath) %>% 
  dplyr::select(Answer.buttheads,
                Answer.close,
                Answer.cometogether,
                Answer.communicate,
                Answer.control,
                Answer.disagreement,
                Answer.worktogether,
                Answer.goal,
                Answer.getalong,
                Answer.overlap,
                Answer.protected,
                Answer.tension,
                Answer.unified,
                Answer.vid_id) 

  data$Answer.vid_id <- gsub("https://s3.us-east-2.amazonaws.com/metaphoric-gestures-x-culture/*", 
                             "\\1", 
                             data$Answer.vid_id)
  return(data)
}

d1 <- load_clean_data("./data/XC_5_western_gest_western_participants.csv")
d2 <- load_clean_data("./data/XC_gest_full_western_participants_5.csv")
d3 <- load_clean_data("./data/XC_gest_full_western_participants_4.csv")
d4 <- load_clean_data("./data/XC_pilot_gest_2.csv")

data <- rbind(d1, d2, d3, d4)

eastern <- data %>%
  filter(grepl("eastern", Answer.vid_id))

western <- data %>%
  filter(grepl("western", Answer.vid_id))

# need to get condition
make_it_pretty <- function(data, condition_name) {
  df <- data %>%
    mutate(condition=Answer.vid_id) %>%
    select(condition, Answer.buttheads,
                Answer.close,
                Answer.cometogether,
                Answer.communicate,
                Answer.control,
                Answer.disagreement,
                Answer.goal,
                Answer.getalong,
                Answer.overlap,
                Answer.protected,
                Answer.tension,
                Answer.unified,
                Answer.worktogether) %>%
    gather("statement_measure", score, 
                Answer.buttheads,
                Answer.close,
                Answer.cometogether,
                Answer.communicate,
                Answer.control,
                Answer.disagreement,
                Answer.goal,
                Answer.getalong,
                Answer.overlap,
                Answer.protected,
                Answer.tension,
                Answer.unified,
                Answer.worktogether)
  return(df)
}


west_cleaned <- make_it_pretty(western, "western")
east_cleaned <- make_it_pretty(eastern, "eastern")
```


Clean up
```{r}
format_indiv_gesture <- function (gesture_num, condition1, condition2) {
  cleaned <- west_cleaned %>%
    mutate(ID=row_number()) %>%
    filter(grepl(gesture_num, condition)) %>%
    mutate(condition=(ifelse(grepl("-1", condition), condition1, condition))) %>%
    mutate(condition=(ifelse(grepl("-0", condition), "original", condition))) %>%
    mutate(condition=(ifelse(grepl("-2", condition), condition2, condition))) 
  
  return(cleaned)
}

gest_1_condition_names <- c("together", "collide")
gest_2_condition_names <- c("separated", "chest")
gest_3_condition_names <- c("no_circle", "palm_up")
gest_4_condition_names <- c("frame", "cover")
gest_5_condition_names <- c("bowl", "forward")

west_gest_1_clean <- format_indiv_gesture("1-", gest_1_condition_names[1], gest_1_condition_names[2])
# all good

west_gest_2_clean <- format_indiv_gesture("2-", gest_2_condition_names[1], gest_2_condition_names[2])
# need more original

west_gest_3_clean <- format_indiv_gesture("3-", "no_circle", "palm_up")

west_gest_4_clean <- format_indiv_gesture("4-", "frame", "cover")
# need more cover

west_gest_5_clean <- format_indiv_gesture("5-", "bowl", "forward")
# need more original and forward

east_gest_1_clean <- east_cleaned %>%
  mutate(ID=row_number()) %>%
  filter(grepl("1-", condition))

east_gest_2_clean <- east_cleaned %>%
  mutate(ID=row_number()) %>%
  filter(grepl("2-", condition))

east_gest_3_clean <- east_cleaned %>%
  mutate(ID=row_number()) %>%
  filter(grepl("3-", condition))
```

## Visualize results
```{r}
create_bar <- function(data) {
  bar_plot <- ggplot(data, aes(x=statement_measure, y=score, fill=condition)) + 
      geom_bar(stat="identity", position="dodge") + 
      facet_wrap(~statement_measure, scale="free")  
  return(bar_plot)
}

create_density <- function(data) {
  ## density of distributions
  density_plot <- ggplot(data, aes(x=score, fill=condition)) + 
    geom_density(alpha=0.3, stat="density", adjust=0.85) +
    facet_wrap(~statement_measure, scale="free") + 
    ggtitle("Unpolite Example distribution of statement ratings") 
  return(density_plot)
}

## get dat violin data

create_violin <- function(data) {
  violin_plot <- ggplot(data, aes(condition, score)) + 
    geom_violin(aes(fill=condition, alpha=0.5), scale="area", draw_quantiles = c(0.25, 0.5, 0.75)) +
    facet_wrap(~statement_measure) + 
    labs(
      title = "Violin plot (density) of response scores per condition by statement"   ,
      caption = "Horizontal lines are drawn at the 0.25, 0.5, and 0.75 quantiles of the distribution."
    )
  return(violin_plot)
}
```


```{r}
west_1_bar <- create_bar(west_gest_1_clean)
west_1_dense <- create_density(west_gest_1_clean)
west_1_violin <- create_violin(west_gest_1_clean) 

#ggsave("unpolite_violin.png", plot=west_1_violin)


### Get plots just for these ones
test_d_1 <- west_gest_1_clean %>%
  filter(statement_measure == "Answer.tension")
test_d_2 <- west_gest_1_clean %>%
  filter(statement_measure == "Answer.worktogether")
test_d <- rbind(test_d_1, test_d_2)

test_plot <- ggplot(test_d, aes(condition, score)) + 
    geom_violin(aes(fill=condition, alpha=0.5), scale="area", draw_quantiles = c(0.25, 0.5, 0.75)) +
    facet_wrap(~statement_measure) + 
  scale_fill_discrete(name = "Gesture Condition", labels = c("Collide", "Original", "Intertwine")) +
  theme(
    legend.key.size = unit(1.5, "cm"),
    legend.key.width = unit(0.5,"cm"),
    legend.text = element_text(size = 10)
  )
ggsave("unpolite_violin_tens_work.png", plot=test_plot)


west_1_west_2_bar <- create_bar(west_gest_2_clean)
west_2_dense <- create_density(west_gest_2_clean)
west_2_violin <- create_violin(west_gest_2_clean)  
#ggsave("entity_violin.png", plot=west_2_violin)

west_3_bar <- create_bar(west_gest_3_clean)
west_3_dense <- create_density(west_gest_3_clean)
west_3_violin <- create_violin(west_gest_3_clean)

west_4_bar <- create_bar(west_gest_4_clean)
west_4_dense <- create_density(west_gest_4_clean)
west_4_violin <- create_violin(west_gest_4_clean)

west_5_bar <- create_bar(west_gest_5_clean)
west_5_dense <- create_density(west_gest_5_clean)
west_5_violin <- create_violin(west_gest_5_clean)

east_1_bar <- create_bar(east_gest_1_clean)
east_1_dense <- create_density(east_gest_1_clean)
east_1_violin <- create_violin(east_gest_1_clean)

east_2_bar <- create_bar(east_gest_2_clean)
east_2_dense <- create_density(east_gest_2_clean)
east_2_violin <- create_violin(east_gest_2_clean)

easteast_3_bar <- create_bar(east_gest_3_clean)
east_3_dense <- create_density(east_gest_3_clean)
east_3_violin <- create_violin(east_gest_3_clean)
```

### Violin plots for each condition
```{r}
west_1_violin
west_2_violin
west_3_violin
west_4_violin
west_5_violin
```

## Stats


### ANOVA

Quickly go through these and see that they match ours...
```{r}
do_anova_per_statement <- function(data, statement) {
  statement_data <- data %>%
    filter(statement_measure==statement)
  res.aov <- aov(score ~ condition, data=statement_data)
  print(statement)
  print(summary(res.aov))
  return(res.aov)
}

do_anova_per_data <- function(data) {
  statements <- c("Answer.buttheads", "Answer.close", "Answer.cometogether", "Answer.communicate",
             "Answer.control", "Answer.disagreement", "Answer.getalong", "Answer.goal",
             "Answer.overlap", "Answer.protected", "Answer.tension", "Answer.unified",
             "Answer.worktogether")
  for (s in statements) {
    print(s)
    a <- do_anova_per_statement(data, s)
    print(summary(a))
    print("========================")
  }
}

do_anova_per_data(west_gest_1_clean)

do_anova_per_data(west_gest_2_clean)

do_anova_per_data(west_gest_3_clean)

do_anova_per_data(west_gest_4_clean)

do_anova_per_data(west_gest_5_clean)

w1 <- do_anova_per_statement(west_gest_1_clean, "Answer.buttheads")
summary(w1)


# pairwise.t.test(w1$score, w1$condition,
#                p.adjust.method = "BH")

```

### T-Tests
```{r include=FALSE}
# t.tests to determine statistical differences between statement responses
get_vals <- function(condition_name, statement, dat) {
  if(dat == "1") {
    dat <- west_gest_1_clean
  } 
  if(dat == "2") {
    dat <- west_gest_2_clean
  }   
  if(dat == "3") {
    dat <- west_gest_3_clean
  } 
  if(dat == "4") {
    dat <- west_gest_4_clean
  } 
  if(dat == "5") {
    dat <- west_gest_5_clean
  }   
  
  ret <- dat %>%
    filter(condition==condition_name) %>%
    filter(statement_measure==statement)
  ret <- ret$score  
  return(ret)
}

do_t_test <- function(cond1, cond2, statement, dat) {
  p <- round(as.numeric(t.test(
            get_vals(cond1, statement, dat),
            get_vals(cond2, statement, dat))[3]), digits=5)
  return(p)
}

do_t_test_adjusted <- function(cond1, cond2, statement, dat) {
  p <- as.numeric(t.test(
            get_vals(cond1, statement, dat),
            get_vals(cond2, statement, dat))[3])
  p_adjusted <- round(p.adjust(p, method="bonferroni", n=13), digits=5)
  return(p_adjusted)
}


sig <- function(p) {
  if(p < 0.0005) {
    return("***")
  }
  if(p < 0.005) {
    return("**")
    }
  if(p < 0.05) {
    return("*")
  }
  return ("")
}

# For some reason can't generalize this to all gestures?
make_table_per_gesture <- function(gest_name, cond1name, cond2name, gest_num) {
  statements <- c("Answer.buttheads", "Answer.close", "Answer.cometogether", "Answer.communicate",
               "Answer.control", "Answer.disagreement", "Answer.getalong", "Answer.goal",
               "Answer.overlap", "Answer.protected", "Answer.tension", "Answer.unified",
               "Answer.worktogether")

  statement <- rep(statements, each=3)
  condition1 <- rep(c(cond1name, cond2name, "original"), 13)
  condition2 <- rep(c("original", cond1name, cond2name), 13)
  # condition1 <- rep(rep(c("original", cond1name, cond2name), 3), 13)
  # condition2 <- rep(rep(c("original", cond1name, cond2name), each=3), 13)
  df <- data.frame(statement, condition1, condition2)   
  
  df$p <- mapply(do_t_test, 
                 as.character(df$condition1), 
                 as.character(df$condition2), 
                 as.character(df$statement),
                 gest_num)
  df$p_adjusted <- mapply(do_t_test_adjusted, 
                 as.character(df$condition1), 
                 as.character(df$condition2), 
                 as.character(df$statement),
                 gest_num)  
  df$sig <- mapply(sig, df$p)
  df$gest_name <- gest_name
  df$statement <- gsub('\\Answer.', '', df$statement)
  return(df)
}


gest_1_sig_table <- make_table_per_gesture("unpolite", gest_1_condition_names[1], gest_1_condition_names[2], "1")
gest_2_sig_table <- make_table_per_gesture("entity", gest_2_condition_names[1], gest_2_condition_names[2], "2")
gest_3_sig_table <- make_table_per_gesture("audience", gest_3_condition_names[1], gest_3_condition_names[2], "3")
gest_4_sig_table <- make_table_per_gesture("anything", gest_4_condition_names[1], gest_4_condition_names[2], "4")
gest_5_sig_table <- make_table_per_gesture("specific", gest_5_condition_names[1], gest_5_condition_names[2], "5")

all_sig_vals <- rbind(gest_1_sig_table, gest_2_sig_table, gest_3_sig_table, gest_4_sig_table, gest_5_sig_table) %>%
  filter(grepl("\\*", sig)) 

# png("sig_vals.png", height = 50*nrow(all_sig_vals), width = 200*ncol(all_sig_vals))
# grid.table(all_sig_vals)
# dev.off()

# export to latex
# print(xtable(all_sig_vals, type = "latex"), file = "sig_vals_ordered.tex")
```

```{r}
all_sig_vals
```


Quickly get average score for a dataset
```{r}
get_avg_score <- function(data, cond, statement) {
  m <- data %>%
    filter(condition==cond) %>%
    filter(statement_measure==statement)
  m <- mean(m$score)  
  return(m)
}

print(get_avg_score(west_gest_4_clean, "original", "Answer.worktogether"))
```















